app/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)

    # Import routes
    from .routes import main_bp
    app.register_blueprint(main_bp)

    return app

app = create_app()

app/main.py
from app import app

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=10000)

app/routes.py
from flask import Blueprint, render_template, request, send_from_directory, Response
import cv2
import os
import time
from ultralytics import YOLO

main_bp = Blueprint('main', __name__)

@main_bp.route("/about")
def about():
    return render_template('about.html')

@main_bp.route("/")
def hello_world():
    return render_template('index.html')

@main_bp.route("/", methods=["GET", "POST"])
def predict_img():
    if request.method == "POST":
        if 'file' in request.files:
            f = request.files['file']
            basepath = os.path.dirname(__file__)
            filepath = os.path.join(basepath, 'uploads', f.filename)
            f.save(filepath)

            file_extension = f.filename.rsplit('.', 1)[1].lower()

            if file_extension == 'jpg':
                img = cv2.imread(filepath)
                model = YOLO('yolov9c.pt')
                detections = model(img, save=True)
            elif file_extension == 'mp4':
                video_path = filepath
                cap = cv2.VideoCapture(video_path)
                frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
                frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
                fourcc = cv2.VideoWriter_fourcc(*'mp4v')
                out = cv2.VideoWriter('output.mp4', fourcc, 30.0, (frame_width, frame_height))
                model = YOLO('yolov9c.pt')
                while cap.isOpened():
                    ret, frame = cap.read()
                    if not ret:
                        break
                    results = model(frame, save=True)
                    res_plotted = results[0].plot()
                    out.write(res_plotted)
                    if cv2.waitKey(1) == ord('q'):
                        break
                cap.release()
                out.release()

    folder_path = 'runs/detect'
    subfolders = [f for f in os.listdir(folder_path) if os.path.isdir(os.path.join(folder_path, f))]
    latest_subfolder = max(subfolders, key=lambda x: os.path.getctime(os.path.join(folder_path, x)))
    image_path = folder_path + '/' + latest_subfolder + '/' + f.filename
    return render_template('index.html', image_path=image_path)

@main_bp.route('/<path:filename>')
def display(filename):
    folder_path = 'runs/detect'
    subfolders = [f for f in os.listdir(folder_path) if os.path.isdir(os.path.join(folder_path, f))]
    latest_subfolder = max(subfolders, key=lambda x: os.path.getctime(os.path.join(folder_path, x)))
    directory = folder_path+'/'+latest_subfolder
    files = os.listdir(directory)
    latest_file = files[0]

    filename = os.path.join(folder_path, latest_subfolder, latest_file)

    file_extension = filename.rsplit('.', 1)[1].lower()

    environ = request.environ
    if file_extension == 'jpg':      
        return send_from_directory(directory,latest_file,environ)
    else:
        return "Invalid file format"

def get_frame():
    folder_path = os.getcwd()
    mp4_files = 'output.mp4'
    video = cv2.VideoCapture(mp4_files)
    while True:
        success, image = video.read()
        if not success:
            break
        ret, jpeg = cv2.imencode('.jpg', image) 
   
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + jpeg.tobytes() + b'\r\n\r\n')   
        time.sleep(0.1)

@main_bp.route("/video_feed")
def video_feed():
    return Response(get_frame(), mimetype='multipart/x-mixed-replace; boundary=frame')

app/templates/about.html
{% extends "base.html" %}

{% block title %} Animal Detection Dashboard {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %} sidebar-mini {% endblock body_class %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="/static/assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="/static/assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- JQVMap -->
  <link rel="stylesheet" href="/static/assets/plugins/jqvmap/jqvmap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="/static/assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="/static/assets/plugins/daterangepicker/daterangepicker.css">
  <!-- summernote -->
  <link rel="stylesheet" href="/static/assets/plugins/summernote/summernote-bs4.min.css">

{% endblock stylesheets %}

{% block content %}
  
<div class="content-wrapper" style="padding: 20px;">
    <section class="content">
      <div class="container-fluid">
        <div class="about-section" style="margin-bottom: 30px;">
          <div class="about-header" style="font-size: 2em; font-weight: bold; margin-bottom: 20px;">About Animal Detection Dashboard</div>
          <div class="about-content" style="font-size: 1.2em; line-height: 1.6;">
            Welcome to the Animal Detection Dashboard, an advanced platform designed to leverage cutting-edge technologies in computer vision and deep learning for detecting animals in images and videos. Our mission is to provide an intuitive and efficient tool for wildlife researchers, enthusiasts, and conservationists to monitor and study animal behavior and population.
          </div>
        </div>
  
        <div class="about-section" style="margin-bottom: 30px;">
          <div class="about-header" style="font-size: 2em; font-weight: bold; margin-bottom: 20px;">Aims and Objectives</div>
          <div class="about-content aims-objectives" style="font-size: 1.1em; font-weight: bold;">
            Our primary aims and objectives are:
            <ul class="objective-list" style="margin-left: 20px; list-style-type: disc;">
              <li>To develop an easy-to-use interface for uploading and processing images and videos for animal detection.</li>
              <li>To utilize state-of-the-art deep learning models for accurate and real-time animal detection.</li>
              <li>To assist wildlife researchers and conservationists in monitoring animal activity and behavior.</li>
              <li>To provide a tool that helps in the conservation efforts by identifying and tracking endangered species.</li>
              <li>To enhance the understanding of animal population dynamics through detailed analysis and reporting.</li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- jQuery UI 1.11.4 -->
  <script src="/static/assets/plugins/jquery-ui/jquery-ui.min.js"></script>
  <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
  <script>
    $.widget.bridge('uibutton', $.ui.button)
  </script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- ChartJS -->
  <script src="/static/assets/plugins/chart.js/Chart.min.js"></script>
  <!-- Sparkline -->
  <script src="/static/assets/plugins/sparklines/sparkline.js"></script>
  <!-- JQVMap -->
  <script src="/static/assets/plugins/jqvmap/jquery.vmap.min.js"></script>
  <script src="/static/assets/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
  <!-- jQuery Knob Chart -->
  <script src="/static/assets/plugins/jquery-knob/jquery.knob.min.js"></script>
  <!-- daterangepicker -->
  <script src="/static/assets/plugins/moment/moment.min.js"></script>
  <script src="/static/assets/plugins/daterangepicker/daterangepicker.js"></script>
  <!-- Tempusdominus Bootstrap 4 -->
  <script src="/static/assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
  <!-- Summernote -->
  <script src="/static/assets/plugins/summernote/summernote-bs4.min.js"></script>
  <!-- overlayScrollbars -->
  <script src="/static/assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.js"></script>
  <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
  <script src="/static/assets/js/pages/dashboard.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/assets/js/demo.js"></script>

{% endblock javascripts %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<!--   <link rel="icon" href="/static/assets/favicon.ico" type="image/x-icon"> -->

  
  <title>
    Flask - {% block title %}{% endblock %} | Aarohi
  </title> 

  {% block stylesheets %}{% endblock stylesheets %}

</head>
<body class="hold-transition {% block body_class %}{% endblock body_class %}">
<div class="wrapper">

    {% include 'navigation.html' %}

    {% include 'sidebar.html' %}

    {% block content %}{% endblock content %}

    {% include 'footer.html' %}

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

</div>
<!-- ./wrapper -->

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

</body>
</html>

app/templates/footer.html
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    &copy; <a target="_blank" rel="noopener noreferrer" href="#">GCIT_ANIMAL_DETECTION</a>
    - coded by <a target="_blank" rel="noopener noreferrer" href="#">GROUP_6</a>
    <div class="float-right d-none d-sm-inline-block">
    </div>
  </footer>

app/templates/index.html
{% extends "base.html" %}

{% block title %} Animal Detection Dashboard {% endblock %}

{% block body_class %} sidebar-mini {% endblock body_class %}

{% block stylesheets %}
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="/static/assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
  <link rel="stylesheet" href="/static/assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <link rel="stylesheet" href="/static/assets/plugins/jqvmap/jqvmap.min.css">
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">
  <link rel="stylesheet" href="/static/assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <link rel="stylesheet" href="/static/assets/plugins/daterangepicker/daterangepicker.css">
  <link rel="stylesheet" href="/static/assets/plugins/summernote/summernote-bs4.min.css">
{% endblock stylesheets %}

{% block content %}
  <div class="content-wrapper">
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Animal_Detection_Dashboard</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
            </ol>
          </div>
        </div>
      </div>
    </div>

    <section class="content">
      <div class="container-fluid">
        <div class="row"></div>
        <div class="row">
          <section class="col-lg-6 connectedSortable">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">
                  <i class="fas fa-chart-pie mr-1"></i>
                  Animal Detection
                </h3>
              </div>
              <div class="card-body">
                <div class="tab-content p-0">
                  <div class="chart tab-pane active" id="revenue-chart" style="position: relative; height: 700px;">
                    <form class="form-signin col-lg-3" method="post" enctype="multipart/form-data" name="form1">
                      <h1 class="h3 mb-3 font-weight-normal">Upload any image or video</h1>
                      <input type="file" name="file" class="form-control-file" id="inputfile" required>
                      <br/>
                      <button class="btn btn-block btn-default btn-sm" type="submit">Predict</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <section class="col-lg-6 connectedSortable">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">
                  <i class="fas fa-chart-pie mr-1"></i>
                  Detection Result
                </h3>
              </div>
              <div class="card-body">
                <div class="tab-content p-0">
                  <div class="chart tab-pane active" id="revenue-chart" style="position: relative; height: 700px;">
                    <img id="my-image" src="{{ url_for('main.display', filename=image_path) }}" style="height:640px; width:640px; display: none;">
                    <img id="my-video-image" src="{{ url_for('main.video_feed') }}" style="height:640px; width:640px; display: none;">
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </section>
  </div>

  <script>
    document.addEventListener("DOMContentLoaded", function() {
      const imagePath = "{{ image_path }}";
      const imageElement = document.getElementById("my-image");
      const videoElement = document.getElementById("my-video-image");
      
      if (imagePath) {
        const fileExtension = imagePath.split('.').pop().toLowerCase();
        if (fileExtension === 'jpg') {
          imageElement.src = "{{ url_for('main.display', filename=image_path) }}";
          imageElement.style.display = "block";
        } else if (fileExtension === 'mp4') {
          videoElement.src = "{{ url_for('main.video_feed') }}";
          videoElement.style.display = "block";
        }
      }
    });
  </script>
{% endblock content %}

{% block javascripts %}
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <script src="/static/assets/plugins/jquery-ui/jquery-ui.min.js"></script>
  <script>
    $.widget.bridge('uibutton', $.ui.button)
  </script>
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/assets/plugins/chart.js/Chart.min.js"></script>
  <script src="/static/assets/plugins/sparklines/sparkline.js"></script>
  <script src="/static/assets/plugins/jqvmap/jquery.vmap.min.js"></script>
  <script src="/static/assets/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
  <script src="/static/assets/plugins/jquery-knob/jquery.knob.min.js"></script>
  <script src="/static/assets/plugins/moment/moment.min.js"></script>
  <script src="/static/assets/plugins/daterangepicker/daterangepicker.js"></script>
  <script src="/static/assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
  <script src="/static/assets/plugins/summernote/summernote-bs4.min.js"></script>
  <script src="/static/assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
  <script src="/static/assets/js/adminlte.js"></script>
  <script src="/static/assets/js/pages/dashboard.js"></script>
  <script src="/static/assets/js/demo.js"></script>
{% endblock javascripts %}

app/templates/navigation.html
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="{{ url_for('main.hello_world') }}" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="{{ url_for('main.about') }}" class="nav-link">About</a>
    </li>
  </ul>



  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Uncomment this section if you want to keep the control-sidebar toggle -->
    <!--
    <li class="nav-item">
      <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
        <i class="fas fa-th-large"></i>
      </a>
    </li>
    -->
  </ul>
</nav>

app/templates/page-blank.html
{% extends "layouts/base.html" %}

{% block title %} Bla
nk Page {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %} sidebar-mini pace-primary {% endblock body_class %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- pace-progress -->
  <link rel="stylesheet" href="/static/assets/plugins/pace-progress/themes/black/pace-theme-flat-top.css">
  <!-- adminlte-->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">

{% endblock stylesheets %}

{% block content %}  

  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Blank Page</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Start</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Title</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
          Start creating your amazing application!
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
          Footer
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- pace-progress -->
  <script src="/static/assets/plugins/pace-progress/pace.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/assets/js/demo.js"></script>

{% endblock javascripts %}

app/templates/scripts.html
<!-- jQuery -->
<script src="/static/assets/plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="/static/assets/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- ChartJS -->
<script src="/static/assets/plugins/chart.js/Chart.min.js"></script>
<!-- Sparkline -->
<script src="/static/assets/plugins/sparklines/sparkline.js"></script>
<!-- JQVMap -->
<script src="/static/assets/plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="/static/assets/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="/static/assets/plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="/static/assets/plugins/moment/moment.min.js"></script>
<script src="/static/assets/plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="/static/assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="/static/assets/plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="/static/assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="/static/assets/js/adminlte.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="/static/assets/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/static/assets/js/demo.js"></script>

app/templates/sidebar.html
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/" class="brand-link">
      <img src="/static/assets/img/pytorch.png" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">ANIMAL DETECTION</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <!-- <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="/static/assets/person.png" class="img-circle elevation-2" alt="User Image">
        </div>

      </div> -->

      <!-- SidebarSearch Form -->
      <!-- <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div> -->

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview {% if 'index' in segment %} menu-open {% endif %}">
            <a href="#" class="nav-link {% if 'index' in segment %} active {% endif %}">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="index.html" class="nav-link {% if 'index.html' in segment %} active {% endif %}">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Image Detection Results</p>
                </a>
              </li>
			  
	

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
  